export const MetricsId = [
  'genres-count',
  'genres-playtime',
  'genres-periods',
  'top-genres-games',
  'genres-rating',
  'recommended-games',
  'developers-playtime',
  'publishers-playtime',
  'studios-periods',
  'developers-rating',
  'publishers-rating',
  'developers-countries',
  'platforms-count',
  'platforms-playtime',
  'platforms-periods',
  'platforms-rating',
  'games-playtime',
  'games-rating',
  'games-periods',
  'games-playdate',
  'games-release',
  'games-countries',
  'top-series'
] as const;
